# Generated by Django 4.2.4 on 2023-10-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_college_created_college_image_college_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='form_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
